apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-envvars
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  {{ range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}