{{ range .Values.jobs }}
{{- if .enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.name }}-{{ .name }}
  labels:
    {{ $.Values.labels | toYaml | nindent 4 }}
  annotations:
    # This ensures the job is recreated on each helm upgrade
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .name }}
        {{- if .image }}
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        {{- else }} 
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- end }}
        {{- if .command }}
          command:  {{ .command }}
        {{- end }}
        {{- if .args }}
        args: {{ .args }}
        {{- end }}
        env:
        {{- range $key, $value := .env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{ if .useDeploymentEnvVars }}
        envFrom:
        - configMapRef:
            name: {{ $.Values.name }}-envvars
        {{- end }}
        {{- if .volumeMounts }}
        volumeMounts:
        {{- range .volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- end }}
        # Include database credentials and other environment variables
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      # Give enough time for slow migrations
      activeDeadlineSeconds: 300
      {{- if .volumes }}
      volumes:
      {{- range .volumes }}
      - name: {{ .name }}
        {{- if .configMap }}
        configMap:
          name: {{ .configMap.name }}
          items:
          {{- range .configMap.items }}
          - key: {{ .key }} 
            path: {{ .path }}
          {{- end }}
        {{- end }}
        {{- if .secret }}
        secret:
          secretName: {{ .secret.name }}
          {{- if .secret.optional }}
          optional: {{ .secret.optional }}
          {{- end }}
          {{- if .secret.items }}
          items:
          {{- range .secret.items }}
          - key: {{ .key }}
            path: {{ .path }}
          {{- end }}
        {{- end }}
        {{- if .emptyDir }}
        emptyDir: {}
        {{- end }}
      {{- end }}
      {{- end }}

---
{{- end }}
{{- end }}